version: '3'
services:
    pg:
      image: postgres
      volumes:
        - ./tmp/db:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: password

    redis:
        image: redis:3.2.8
        environment:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
          - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
          - '6379:6379'
        volumes:
          - 'redis_data:/redis/data'

    app:
      build: .
      volumes:
        - .:/app
      ports:
        - "3000:3000"
      command: bin/rails server --port 3000 --binding 0.0.0.0
      depends_on:
        - pg
        - redis

volumes:
  redis_data:
    driver: local
