version: '3'
services:
    pg:
      image: postgres
      volumes:
        - ./tmp/db:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      ports:
        - '5432:5432'

    redis:
        image: redis:3.2.8
        environment:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
          - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
          - '6379:6379'
        volumes:
          - 'redis_data:/redis/data'

    app:
      build: .
      volumes:
        - .:/app
      ports:
        - "3000:3000"
      entrypoint: /app/entrypoint.sh
      depends_on:
        - pg
        - redis

volumes:
  redis_data:
    driver: local
