default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: pg

development:
  <<: *default
  database: thermostat_development

test:
  <<: *default
  database: thermostat_test
